export const metrics = [{metric:'1 rep squat',
parent:'undefined',
drivers:['Quality of mobility', 'Current 1 rep squat', 'Diet', 'Current programming']},
{metric:'Quality of mobility',
parent:'1 rep squat',
drivers:['Flexibility']},
{metric:'Flexibility',
parent:'Quality of mobility',
drivers:['Ankles', 'Knees', 'Hips', '']},
{metric:'Ankles',
parent:'Flexibility',
drivers:[]},
{metric:'1 rep squat',
parent:'undefined',
drivers:['Quality of mobility', 'Current 1 rep squat', 'Diet', 'Current programming']},
{metric:'Quality of mobility',
parent:'1 rep squat',
drivers:['Flexibility']},
{metric:'Flexibility',
parent:'Quality of mobility',
drivers:['Knees', 'Hips', '']},
{metric:'Knees',
parent:'Flexibility',
drivers:[]},
{metric:'1 rep squat',
parent:'undefined',
drivers:['Quality of mobility', 'Current 1 rep squat', 'Diet', 'Current programming']},
{metric:'Quality of mobility',
parent:'1 rep squat',
drivers:['Flexibility']},
{metric:'Flexibility',
parent:'Quality of mobility',
drivers:['Hips', '']},
{metric:'Hips',
parent:'Flexibility',
drivers:[]},
{metric:'1 rep squat',
parent:'undefined',
drivers:['Current 1 rep squat', 'Diet', 'Current programming']},
{metric:'Current 1 rep squat',
parent:'1 rep squat',
drivers:['Flexibility']},
{metric:'Flexibility',
parent:'Current 1 rep squat',
drivers:['']},
{metric:'1 rep squat',
parent:'undefined',
drivers:['Diet', 'Current programming']},
{metric:'Diet',
parent:'1 rep squat',
drivers:['Calories', 'Protein intake', 'Healthy food']},
{metric:'Calories',
parent:'Diet',
drivers:['']},
{metric:'1 rep squat',
parent:'undefined',
drivers:['Diet', 'Current programming']},
{metric:'Diet',
parent:'1 rep squat',
drivers:['Protein intake', 'Healthy food']},
{metric:'Protein intake',
parent:'Diet',
drivers:['']},
{metric:'1 rep squat',
parent:'undefined',
drivers:['Diet', 'Current programming']},
{metric:'Diet',
parent:'1 rep squat',
drivers:['Healthy food']},
{metric:'Healthy food',
parent:'Diet',
drivers:['']},
{metric:'1 rep squat',
parent:'undefined',
drivers:['Current programming']},
{metric:'Current programming',
parent:'1 rep squat',
drivers:['Legs', 'Glutes', 'Core']},
{metric:'Legs',
parent:'Current programming',
drivers:['']},
{metric:'1 rep squat',
parent:'undefined',
drivers:['Current programming']},
{metric:'Current programming',
parent:'1 rep squat',
drivers:['Glutes', 'Core']},
{metric:'Glutes',
parent:'Current programming',
drivers:['']},
{metric:'1 rep squat',
parent:'undefined',
drivers:['Current programming']},
{metric:'Current programming',
parent:'1 rep squat',
drivers:['Core']},
{metric:'Core',
parent:'Current programming',
drivers:['']}]